# Generated by Django 5.1.2 on 2024-10-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.TextField()),
                ('stress', models.PositiveIntegerField()),
                ('activity', models.PositiveIntegerField()),
                ('sleep', models.PositiveIntegerField()),
                ('biometrics', models.CharField(max_length=255)),
                ('medications', models.CharField(max_length=255)),
                ('family_history', models.TextField()),
            ],
        ),
    ]
